title: All Things macOS
author: Elio Labbia
description: >
  Apple Silicon M1, Monterey, Ventura, MacBook Pro, Mac Window Management, Finder, System Utilities, Mac Menu Bar Apps and whatnot.

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-feed
  - jekyll-redirect-from

minima_reboot:
  date_format: "%b %-d, %Y"
  date_format_short: "%b %-d"

header_pages:
- about.md
- posts.md
- github.md

footer_icons:
- username: Elio Labbia
  url: https://labbia.github.io/
  icon: icon-github.svg

paginate: 5

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - minima-reboot.gemspec
